export const FETCH_LOGIN_STATUS = 'FETCH_LOGIN_STATUS';
export const RECEIVE_LOGIN_STATUS = 'RECEIVE_LOGIN_STATUS';
export const FAILED_LOGIN_STATUS = 'FAILED_LOGIN_STATUS';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const SUCCESS_LOGOUT = 'SUCCESS_LOGOUT';
export const FAILED_LOGOUT = 'FAILED_LOGOUT';
